import 'package:get/get.dart';

class Translation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "welcome message":
              "Discover the endless beauty of Vietnam through meaningful Game Tours, receive special gifts after completing a trip and much more...",
          "welcome to": "Welcome to",
          "intro-title1": "No Matter Where You Are",
          "intro-title2": "Explore Nearby Stuffs",
          "intro-title3": "Realtime Travel Guide",
          "intro-description1":
              "Access to important information about your destination before and during your travel...",
          "intro-description2":
              "Explore nearby hotels & restaurants near every tourist spot with the easiest way...",
          "intro-description3":
              "Get directions, costs, and other travel-related stuff in one place...",
          "get started": "Get Started",
          "explore country": "Explore Việt Nam",
          "search places": "Search Quest",
          "popular places": "Popular Places",
          "special state-1 places": "Places in Sylhet",
          "special state-2 places": "Places in Chittagong",
          "recently added": "Recently Added",
          "recommended places": "Recommended Places",
          "people like this": "People like this",
          "todo": "To Do",
          "you may also like": "You might also like",
          "travel guide": "Travel Guide",
          "nearby hotels": "Nearby Hotels",
          "nearby restaurants": "Nearby Restaurants",
          "steps": "Steps",
          "estimated cost = ": "Estimated Cost = ",
          "distance = ": "Distance = ",
          "no hotels found": "No Hotels Found",
          "no restaurants found": "No Restaurants Found",
          "we didn't find any nearby hotels in this area":
              "We haven't found any nearby hotels in this area",
          "we didn't find any nearby restaurants in this area":
              "We haven't found any nearby restaurants in this area",
          "user reviews": "User Reviews",
          "write a review": "Write A Review",
          "no internet": "No internet commection!",
          "no comments found": "No comments found",
          "be the first to comment": "Be the first to comment",
          "recently added places": "Recently Added Places",
          "search & explore": "Search & Explore Quest",
          "recent searchs": "Recent Search(s)",
          "search for places": "Search for places",
          "search-description":
              "You haven't searched for any items yet.\n Try now - we will help you!",
          "we have found": "We have found",
          "no places found": "No places found",
          "try again": "Try again!",
          "states": "States",
          "blogs": "Blogs",
          "bookmarks": "History",
          "saved places": "Purchased quests",
          "saved blogs": "Playing history",
          "sign in first": "Sign In First",
          "sign in to save your favourite places here":
              "Sign in to save your purchased history here",
          "sign in to save your favourite blogs here":
              "Sign in to display your playing history here",
          "no blogs found": "No playing history Found",
          "save your favourite places here": "Save your purchased history here",
          "save your favourite blogs here": "Save your playing history here",
          "skip": "Skip",
          "check your internet connection!": "Check your internet connection!",
          "something is wrong. please try again.":
              "Something is wrong. Please try again.",
          "sign in": "Sign In",
          "cancel": "Cancel",
          "no sign in title": "Sign in first to access this feature",
          "no sign in subtitle":
              "You haven't signed in yet. Please sign in to unlock this feature",
          "comments": "Comments",
          "write a comment": "Write A Comment",
          "no content": "No contents found",
          "delete?": "Delete?",
          "delete from database?": "Want to delete this item?",
          "flag this comment": "Flag this comment",
          "unflag this comment": "Unflag this comment",
          "report": "Report",
          "delete": "Delete",
          "report-info": "Your report has been sent successfully to the admins",
          "report-info1":
              "Thanks for your report. We will repond within 24 hours.",
          "report-guest": "Sign In is Required!",
          "report-guest1": "You have to sign in to report about any comments",
          "comment flagged": "This comment has been flagged!",
          "notifications": "Notifications",
          "notification details": "Notification Details",
          "profile": "Profile",
          "general setting": "General Settings",
          "login": "Login",
          "get notifications": "Get Notifications",
          "contact us": "Contact Us",
          "rate this app": "Rate this app",
          "licence": "Licence",
          "privacy policy": "Privacy Policy",
          "about us": "About Us",
          "logout": "Logout",
          "edit profile": "Edit Profile",
          "update profile": "Update Profile",
          "updated successfully": "Updated Successfully",
          "enter new name": "Enter new name",
          "logout title": "Do you really want to logout from the app?",
          "yes": "Yes",
          "no": "No",
          "language": "Language",
          "select language": "Select Language",
          "buy now": "Purchase this app",
          "buy now subtitle":
              "Buy the full source code here and build the app for your country",
          "facebook": "Facebook Page",
          "youtube": "Youtube Channel",
          "no notifications": "No notifications found",
          "no blogs": "No blogs found",
          "no playing history found": "No Playing History Found",
          "playing history": "Playing History",
          "your reward": "Your Reward",
          "quest type": "Quest Type",
          "home": "Home",
          "reward": "Reward",
          "history": "History",
          "waiting loading data...": "Waiting Loading Data...",
          "waiting.....": "waiting.....",
          "my quest": "My Quest",
          "minutes": "minutes",
          "buy": "Buy",
          "item": "Item:",
          "quantity": "Quantity",
          "enter voucher here": "Enter voucher here",
          "total price": "Total price",
          "payment status": "Payment status",
          "not yet paid": "Not yet paid",
          "play code": "Play Code : ",
          "copy": "Copy",
          "cofirm payment": "Cofirm payment",
          "cofirm": "Confirm",
          "play now": "Play Now",
          "no reward found": "No reward found!",
          "change password": "Change Password",
          "enter old password": "Enter old password",
          "old password can't be empty": "Old password can't be empty",
          "enter new password": "Enter new password",
          "new password can't be empty": "New password can't be empty",
          "cofirm new password": "Cofirm new password",
          "new password and cofirm password must be the same!":
              "New password and Cofirm password must be the same!",
          "sign in with google": "Sign In with Google",
          "sign in with facebook": "Sign In with Facebook",
          "sign in with user": "Sign In with Username/Password",
          "email": "Email",
          "email is required": "Email is Required",
          "invalid email": "Invalid Email",
          "password": "Password",
          "password is required": "Password is Required",
          "password must minimum six characters":
              "Password must minimum eight characters",
          "password at least one uppercase letter, one lowercase letter, one specical character and one number":
              "Password at least one uppercase letter, one lowercase letter, one specical character and one number",
          "log in": "Log In",
          "forgot password?": "Forgot password?",
          "not a member? sign up now": "Not a member? Sign up now",
          "please enter your email": "Please enter your Email",
          "cofirm password": "Cofirm password",
          "cofirm password is required": "Cofirm password is Required",
          "password and cofirm password must be the same!":
              "Password and Cofirm password must be the same!",
          "register": "Register",
          "time up": "Time up",
          "time remaining": "Time remaining:",
          "ok": "OK",
          "quests that have entered the game cannot be reused. do you want to confirm?":
              "Quests that have entered the game cannot be reused. Do you want to confirm?",
          "copy code": "Copy Code",
          "each question you will get 300 points":
              "Each question you will get 300 points",
          "you will be answered up to 5 times for a question":
              "You will be answered up to 5 times for a question",
          "the 5th time you will be shown the answer":
              "With text answer the 5th time you will be shown the answer",
          "with image scan quest if you answer 5th time wrong you will be move to next task":
              "With image scan quest if you answer 5th time wrong you will be move to next task",
          "for each wrong answer, 50 points will be deducted":
              "For each wrong answer, 50 points will be deducted",
          "using seggestion will be deducted 75 points (1 time)":
              "Using suggestion will be deducted 75 points (1 time)",
          "rulepage": "RulePage",
          "progress page ": "Information",
          "NUM OF QUESTION ": "NUM OF QUESTION ",
          "submit": "Submit",
          "suggestion": "Suggestion",
          "you should know": "You should know",
          "total distance:": "Total distance: ",
          "total time:": "Total time: ",
          "number of question:": "Number of question: ",
          "don't have any comments": "Don't have any comments",
          "Customer not found": "Customer not found",
          "success": "Success",
          "check you email to get new password":
              "Check you email to get new password",
          "error": "Error",
          "error change password": "Error change password",
          "success change password": "Success change password",
          "user already exists": "User already exists",
          "error register": "Error register",
          "please confim you email before login!":
              "Please confim you email before login!",
          "user not exist or wrong username and password":
              "User not exist or wrong username and password",
          "only 1 answer left": "Only 1 answer left",
          "wrong answer": "Wrong Answer",
          "right answer": "Right Answer",
          "congratulations": "Congratulations",
          "error ticket": "Error ticket",
          "previous quest not over. please contact the hotline for support":
              "Previous Quest Not Over. Please contact the hotline for support",
          "please go to this address to start the quest:":
              "Please go to this address to start the Quest:",
          "open map": "Open Google map",
          "complete quest: ": "Complete quest: ",
          "time": "Time",
          "point": "Point",
          "how is your trip?": "How is your trip?",
          "rating quest": "Rating quest",
          "discount code is not valid": "Discount code is not valid",
          "voucher is wrong format": "Voucher is wrong format",
          "skip question": "Skip question",
          "show suggestion": "show suggestion",
          "you will be move to next task": "You will be move to next task",
          "do you want to skip this question?":
              "Do you want to skip this question(you will be minus 100 point)?",
          "skip success": "Skip success",
          "try again next time": "Try again next time",
          "error when skip questtion": "Error when skip questtion",
          "description page": "Infomation",
          "story page": "Story page",
          "next": "Next",
          "account not allowed to login": "Account not allowed to login",
          "update profile success": "Update profile success",
          "update profile error": "Update profile error",
          "play code not exist or expired": "Play code not exist or expired",
          "please try again": "Please try again",
          "reset": "Reset",
          "scan qr code": "Scan QR code",
          "payment page": "Payment Page",
          "temporary amount": "Temporary amount",
          "amount reduced": "Amount reduced",
          "discount": "DISCOUNT",
          "payment success": "Payment Success",
          "please find and take a photo of something similar to the one below (please let the app use your camera)":
              "Please find and take a photo of something similar to the one below (Please let the app use your camera)",
          "question no": "Question No",
          "info purchase": "Info purchase",
          "do you want to show suggestion(you will be minus 75 point)":
              "Do you want to show suggestion(you will be minus 75 point)",
          "You will lose this turn and cannot play again":
              "You will lose this turn and cannot play again",
          "Score achieved": "Score achieved",
          "Buy again": "Buy again",
          "You received a discount code": "You received a discount code",
          "You get a discount code for your next order":
              "You get a discount code for your next order",
          "submitComment": "Submit",
          "Khong tim thay quest nao": "Don't have any quest",
          "Mua quest di nha": "Please buy some quest",
          "Cau hoi chua co goi y": "This question has no suggestion",
          "send a message..": "Send a message...",
          "Quest is not ready yet": "Quest is not ready yet",
          "show more": "Show more",
          "collapse": "Collapse",
          "in put play code": "Input play code",
          "payment detail": "Payment Detail",
          "enter new address": "Enter new address",
          "address can't be empty": "Address can't be empty",
          "male": "Male",
          "female": "Female",
          "finish": "Finish",
          "system busy": "System busy"
        },
        'vn': {
          "welcome message":
              "Khám phá nét đẹp vô tận của Việt Nam thông qua những Game Tour đầy ý nghĩa, nhận những phần quà đặc sắc sau khi hoàn thành một chuyến đi và còn nhiều hơn nữa...",
          "welcome to": "Chào mừng đến với",
          "intro-title1": "Không quan trọng bạn đang ở đâu",
          "intro-title2": "Khám phá Nội dung lân cận",
          "intro-title3": "Hướng dẫn du lịch theo thời gian thực",
          "intro-description1":
              "Truy cập thông tin quan trọng về điểm đến của bạn trước và trong chuyến du lịch ...",
          "intro-description2":
              "Khám phá các khách sạn và nhà hàng lân cận gần mọi điểm du lịch bằng cách dễ dàng nhất ...",
          "intro-description3":
              "Nhận chỉ đường, chi phí và những thứ khác liên quan đến du lịch ở một nơi ...",
          "get started": "Bắt đầu",
          "explore country": "Khám phá Việt Nam",
          "search places": "Tìm kiếm quest",
          "popular places": "Địa điểm nổi tiếng",
          "special state-1 places": "Địa điểm ở Sylhet",
          "special state-2 places": "Địa điểm ở Chittagong",
          "recently added": "Đã thêm gần đây",
          "recommended places": "Địa điểm được đề xuất",
          "people like this": "Mọi người thích điều này",
          "todo": "Việc cần làm",
          "you may also like": "Bạn cũng có thể thích",
          "travel guide": "Hướng dẫn du lịch",
          "nearby hotels": "Khách sạn lân cận",
          "nearby restaurants": "Nhà hàng lân cận",
          "steps": "Các bước",
          "estimated cost = ": "Chi phí ước tính =",
          "distance = ": "Khoảng cách = ",
          "no hotels found": "Không tìm thấy khách sạn",
          "no restaurants found": "Không tìm thấy nhà hàng",
          "we didn't find any nearby hotels in this area":
              "Chúng tôi không tìm thấy bất kỳ khách sạn lân cận nào trong khu vực này",
          "we didn't find any nearby restaurants in this area":
              "Chúng tôi không tìm thấy bất kỳ nhà hàng lân cận nào trong khu vực này",
          "user reviews": "Đánh giá của người dùng",
          "write a review": "Viết đánh giá",
          "no internet": "Không có kết nối mạng!",
          "no comments found": "Không tìm thấy nhận xét nào",
          "be the first to comment": "Hãy là người đầu tiên nhận xét",
          "recently added places": "Địa điểm được thêm gần đây",
          "search & explore": "Tìm kiếm Quest",
          "recent searchs": "Các Tìm kiếm Gần đây",
          "search for places": "Tìm kiếm địa điểm",
          "search-description":
              "Bạn chưa tìm kiếm bất kỳ mục nào. \n Hãy thử ngay bây giờ - chúng tôi sẽ giúp bạn!",
          "we have found": "Chúng tôi đã tìm thấy",
          "no places found": "Không tìm thấy địa điểm",
          "try again": "Thử lại!",
          "states": "Bang",
          "blogs": "Blog",
          "bookmarks": "Dấu trang",
          "saved places": "Địa điểm đã lưu",
          "saved blogs": "Blog đã lưu",
          "sign in first": "Đăng nhập trước",
          "sign in to save your favourite places here":
              "Đăng nhập để lưu các địa điểm yêu thích của bạn",
          "sign in to save your favourite blogs here":
              "Đăng nhập để lưu các blog yêu thích của bạn",
          "no blogs found": "Không tìm thấy blog",
          "save your favourite places here": "Lưu địa điểm yêu thích của bạn",
          "save your favourite blogs here": "Lưu các blog yêu thích của bạn",
          "skip": "Bỏ qua",
          "check your internet connection!":
              "Kiểm tra kết nối Internet của bạn!",
          "something is wrong. please try again.":
              "Đã xảy ra lỗi. Vui lòng thử lại.",
          "sign in": "Đăng nhập",
          "cancel": "Hủy bỏ",
          "no sign in title": "Đăng nhập trước để truy cập tính năng này",
          "no sign in subtitle":
              "Bạn chưa đăng nhập. Vui lòng đăng nhập để mở khóa tính năng này",
          "comments": "Nhận xét",
          "write a comment": "Viết bình luận",
          "no content": "Không tìm thấy nội dung",
          "delete?": "Xóa bỏ?",
          "delete from database?": "Bạn muốn xóa mục này?",
          "flag this comment": "Gắn cờ cho nhận xét này",
          "unflag this comment": "Bỏ gắn thẻ cho nhận xét này",
          "report": "Báo cáo",
          "delete": "Xóa",
          "report-info":
              "Báo cáo của bạn đã được gửi thành công tới quản trị viên",
          "report-info1":
              "Cảm ơn bạn đã báo cáo. Chúng tôi sẽ trả lời trong vòng 24 giờ.",
          "report-guest": "Đăng nhập là Bắt buộc!",
          "report-guest1": "Bạn phải đăng nhập để báo cáo về mọi nhận xét",
          "comment flagged": "Nhận xét này đã bị gắn cờ!",
          "notifications": "Thông báo",
          "notification details": "Chi tiết thông báo",
          "profile": "Hồ sơ",
          "general setting": "Cài đặt chung",
          "login": "Đăng nhập",
          "get notifications": "Nhận thông báo",
          "contact us": "Liên hệ với chúng tôi",
          "rate this app": "Xếp hạng ứng dụng này",
          "licence": "Giấy phép",
          "privacy policy": "Chính sách bảo mật",
          "about us": "Về chúng tôi",
          "logout": "Đăng xuất",
          "edit profile": "Chỉnh sửa hồ sơ",
          "update profile": "Cập nhật hồ sơ",
          "updated successfully": "Đã cập nhật thành công",
          "enter new name": "Nhập tên mới",
          "logout title": "Bạn có thực sự muốn đăng xuất khỏi ứng dụng không?",
          "yes": "Có",
          "no": "Không",
          "language": "Ngôn ngữ",
          "select language": "Chọn ngôn ngữ",
          "buy now": "Mua ứng dụng này",
          "buy now subtitle":
              "Mua toàn bộ mã nguồn tại đây và xây dựng ứng dụng cho quốc gia của bạn",
          "facebook": "Facebook",
          "youtube": "Youtube",
          "no notifications": "Không tìm thấy thông báo",
          "no blogs": "Không tìm thấy blog nào",
          "no playing history found": "Không tìm thấy lịch sử chơi nào",
          "playing history": "Lịch sử chơi",
          "your reward": "Phần thưởng của bạn",
          "quest type": "Các Thể Loại",
          "home": "Trang chủ",
          "reward": "Quà",
          "history": "Lịch sử",
          "waiting loading data...": "Đang tải dữ liệu...",
          "waiting.....": "Đang tải.....",
          "my quest": "Quest của tôi",
          "minutes": "phút",
          "buy": "Mua",
          "item": "Vật phẩm:",
          "quantity": "Số Lượng",
          "enter voucher here": "Nhập mã giảm giá",
          "total price": "Tổng tiền",
          "payment status": "Thông tin thanh toán",
          "not yet paid": "CHƯA THANH TOÁN",
          "play code": "Mã chơi : ",
          "copy": "Sao chép",
          "cofirm payment": "Xác nhận thanh  toán",
          "cofirm": "Xác nhận",
          "play now": "Chơi ngay",
          "no reward found": "Không tìm thấy phần thưởng nào!",
          "change password": "Đổi mật khẩu",
          "enter old password": "Nhập mật khẩu củ",
          "old password can't be empty": "Mật khẩu củ không thể để trống",
          "enter new password": "Nhập mật khẩu mới",
          "new password can't be empty": "Mật khẩu mới không thể để trống",
          "cofirm new password": "Nhập lại mật khẩu mới",
          "new password and cofirm password must be the same!":
              "Mật khẩu mới và Xác nhận phải giống nhay",
          "sign in with google": "Đăng nhập với Google",
          "sign in with facebook": "Đăng nhập với Facebook",
          "sign in with user": "Đăng nhập với Tài khoản",
          "email": "Email",
          "email is required": "Email không được để trống",
          "invalid email": "Sai định dạng email",
          "password": "Mật Khẩu",
          "password is required": "Mật khẩu không được để trống",
          "password must minimum six characters":
              "Mật khẩu cần ít nhất 8 kí tự",
          "password at least one uppercase letter, one lowercase letter, one specical character and one number":
              "Mật khẩu phải có 1 chữ cái in hoa, 1 chữ cái thường, 1 ký tự đặc biệt và một số",
          "log in": "Đăng nhập",
          "forgot password?": "Quên mật khẩu?",
          "not a member? sign up now": "Không phải thành viên? Đăng ký ngay",
          "please enter your email": "Vui lòng nhập email của bạn",
          "cofirm password": "Xác nhận mật khẩu",
          "cofirm password is required":
              "Xác nhận mật khẩu không được để trống",
          "password and cofirm password must be the same!":
              "Mật khẩu và xác nhận phải giống nhau!",
          "register": "Đăng ký",
          "time up": "Hết giờ",
          "time remaining": "Thời gian còn lại:",
          "ok": "Đồng ý",
          "quests that have entered the game cannot be reused. do you want to confirm?":
              "Quest đã vào chơi không được sử dụng lại. Bạn có muốn xác nhận?",
          "copy code": "Sao chép mã",
          "each question you will get 300 points":
              "Mỗi câu hỏi bạn sẽ có 300 điểm",
          "you will be answered up to 5 times for a question":
              "Bạn sẽ được trả lời tối đa 5 lần cho một câu hỏi",
          "the 5th time you will be shown the answer":
              "Với câu hỏi trả lời bằng chữ Lần 5 bạn sẽ được hiện đáp án",
          "with image scan quest if you answer 5th time wrong you will be move to next task":
              "Với câu hỏi quét ảnh nêu bạn trả lời sai lần thứ 5 bạn sẽ được chuyển qua câu hỏi tiếp theo",
          "for each wrong answer, 50 points will be deducted":
              "Mỗi lần trả lời sai sẽ bị trừ 50 điểm",
          "using seggestion will be deducted 75 points (1 time)":
              "Sử dụng gợi ý sẽ bị trừ 75 điểm (1 lần)",
          "rulepage": "Trang quy tắc",
          "progress page ": "Thông tin",
          "NUM OF QUESTION ": "SỐ CÂU HỎI ",
          "submit": "Trả lời",
          "suggestion": "Gợi ý",
          "you should know": "Bạn nên biết",
          "total distance:": "Tổng quãng đường: ",
          "total time:": "Tổng thời gian: ",
          "number of question:": "Số lượng câu đố: ",
          "don't have any comments": "Không có comment nào",
          "Customer not found": "Người dùng không tồn tại",
          "success": "Thành công",
          "check you email to get new password":
              "Kiểm tra mail của bạn để nhận mật khẩu mới",
          "error": "Lỗi",
          "error change password": "Lỗi khi đổi mật khẩu",
          "success change password": "Đổi mật khẩu thành công",
          "user already exists": "Người dùng đã tồn tại",
          "error register": "Lỗi khi đăng ký",
          "please confim you email before login!":
              "Vui lòng xác nhận tài khoản của bạn qua mail trước khi đăng nhập!",
          "user not exist or wrong username and password":
              "Người dùng không tông tại hoặc sai tài khoản/mật khẩu",
          "only 1 answer left": "Chỉ còn 1 lần trả lời",
          "wrong answer": "Trả lời sai",
          "right answer": "Trả lời đúng",
          "congratulations": "Chúc mừng!",
          "error ticket": "Vé lỗi",
          "previous quest not over. please contact the hotline for support":
              "Quest trước chưa được hoàn thành vui lòng liên hệ hotline để hỗ trợ",
          "please go to this address to start the quest:":
              "Bạn vui lòng đến địa chỉ này để bắt đầu Quest:",
          "open map": "Mở Google map",
          "complete quest: ": "Hoàn thành quest: ",
          "time": "Thời gia",
          "point": "Điểm",
          "how is your trip?": "Trải nghiệm của bạn thế nào?",
          "rating quest": "Đánh giá chất lượng quest",
          "discount code is not valid": "Mã giảm giá không hợp lệ",
          "voucher is wrong format": "Mã giảm giá sai định dạng",
          "skip question": "Bỏ qua câu hỏi",
          "show suggestion": "Hiện gợi ý",
          "you will be move to next task":
              "Bạn sẽ được chuyển qua câu hỏi tiếp theo",
          "do you want to skip this question?":
              "Bạn muốn bỏ qua câu hỏi này(bạn sẽ bị trừ 100 điểm)?",
          "skip success": "Bỏ qua thành công",
          "try again next time": "Hãy cố gắng hơn vào lần sau nhé",
          "error when skip questtion": "Lỗi khi bỏ qua câu hỏi",
          "description page": "Thông tin",
          "story page": "Trang câu chuyện",
          "next": "Tiếp tục",
          "account not allowed to login": "Tài khoản không được phép đăng nhập",
          "update profile success": "Câp nhật thông tin thành công",
          "update profile error": "Lỗi khi cập nhật thông tin",
          "play code not exist or expired":
              "Mã chơi không tồn tại hoặc đã hết hạn",
          "please try again": "Vui lòng thử lại",
          "reset": "Đặt lại",
          "scan qr code": "Quét mã QR",
          "payment page": "Trang thanh toán",
          "temporary amount": "Tạm tính",
          "amount reduced": "Tiền giảm",
          "discount": "GIẢM",
          "payment success": "Thanh toán thành công",
          "please find and take a photo of something similar to the one below (please let the app use your camera)":
              "Bạn hãy tìm và chụp ảnh của giống với ảnh bên dưới nhé(Vui lòng cho app sử dụng camera của bạn)",
          "question no": "Câu hỏi số",
          "info purchase": "Thông tin mua hàng",
          "do you want to show suggestion(you will be minus 75 point)":
              "Bạn có muốn hiện gợi ý không (Bạn sẽ bị trừ 75 điểm)",
          "You will lose this turn and cannot play again":
              "Bạn sẽ mất lượt này và không thể chơi lại",
          "Score achieved": "Số điểm đạt được",
          "Buy again": "Mua lại",
          "You received a discount code": "Bạn đã nhận được một mã giảm giá",
          "You get a discount code for your next order":
              "Bạn nhận được mã giảm giá cho đơn hàng tiếp theo",
          "submitComment": "Gửi",
          "Khong tim thay quest nao": "Không tìm thấy quest nào",
          "Mua quest di nha": "Hãy mua quest đi nhé",
          "Cau hoi chua co goi y": "Câu hỏi này không có gợi ý",
          "send a message..": "Gửi tin nhắn...",
          "Quest is not ready yet": "Quest chưa sẵn sàng",
          "show more": "Xem thêm",
          "collapse": "Thu gọn",
          "in put play code": "Nhập mã chơi",
          "payment detail": "Chi tiết đơn hàng",
          "enter new address": "Nhập địa chỉ mới",
          "address can't be empty": "Địa chỉ không thể để trống",
          "male": "Nam",
          "female": "Nữ",
          "finish": "Kết thúc",
          "system busy": "Hệ thống bận"
        }
      };
}
