import 'package:get/get.dart';

class Translation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "welcome message":
              "Explore every famous place in Bangladesh and find nearby hotels and restaurants with the easiest way. Get realtime directions, estimated costs, travel blogs, and more...",
          "welcome to": "Welcome to",
          "intro-title1": "No Matter Where You Are",
          "intro-title2": "Explore Nearby Stuffs",
          "intro-title3": "Realtime Travel Guide",
          "intro-description1":
              "Access to important information about your destination before and during your travel...",
          "intro-description2":
              "Explore nearby hotels & restaurants near every tourist spot with the easiest way...",
          "intro-description3":
              "Get directions, costs, and other travel-related stuff in one place...",
          "get started": "Get Started",
          "explore country": "Explore Việt Nam",
          "search places": "Search Quest",
          "popular places": "Popular Places",
          "special state-1 places": "Places in Sylhet",
          "special state-2 places": "Places in Chittagong",
          "recently added": "Recently Added",
          "recommended places": "Recommended Places",
          "people like this": "People like this",
          "todo": "To Do",
          "you may also like": "You might also like",
          "travel guide": "Travel Guide",
          "nearby hotels": "Nearby Hotels",
          "nearby restaurants": "Nearby Restaurants",
          "steps": "Steps",
          "estimated cost = ": "Estimated Cost = ",
          "distance = ": "Distance = ",
          "no hotels found": "No Hotels Found",
          "no restaurants found": "No Restaurants Found",
          "we didn't find any nearby hotels in this area":
              "We haven't found any nearby hotels in this area",
          "we didn't find any nearby restaurants in this area":
              "We haven't found any nearby restaurants in this area",
          "user reviews": "User Reviews",
          "write a review": "Write A Review",
          "no internet": "No internet commection!",
          "no comments found": "No comments found",
          "be the first to comment": "Be the first to comment",
          "recently added places": "Recently Added Places",
          "search & explore": "Search & Explore Places",
          "recent searchs": "Recent Search(s)",
          "search for places": "Search for places",
          "search-description":
              "You haven't searched for any items yet.\n Try now - we will help you!",
          "we have found": "We have found",
          "no places found": "No places found",
          "try again": "Try again!",
          "states": "States",
          "blogs": "Blogs",
          "bookmarks": "History",
          "saved places": "Purchased quests",
          "saved blogs": "Playing history",
          "sign in first": "Sign In First",
          "sign in to save your favourite places here":
              "Sign in to save your purchased history here",
          "sign in to save your favourite blogs here":
              "Sign in to display your playing history here",
          "no blogs found": "No playing history Found",
          "save your favourite places here": "Save your purchased history here",
          "save your favourite blogs here": "Save your playing history here",
          "skip": "Skip",
          "check your internet connection!": "Check your internet connection!",
          "something is wrong. please try again.":
              "Something is wrong. Please try again.",
          "sign in": "Sign In",
          "cancel": "Cancel",
          "no sign in title": "Sign in first to access this feature",
          "no sign in subtitle":
              "You haven't signed in yet. Please sign in to unlock this feature",
          "comments": "Comments",
          "write a comment": "Write A Comment",
          "no content": "No contents found",
          "delete?": "Delete?",
          "delete from database?": "Want to delete this item?",
          "flag this comment": "Flag this comment",
          "unflag this comment": "Unflag this comment",
          "report": "Report",
          "delete": "Delete",
          "report-info": "Your report has been sent successfully to the admins",
          "report-info1":
              "Thanks for your report. We will repond within 24 hours.",
          "report-guest": "Sign In is Required!",
          "report-guest1": "You have to sign in to report about any comments",
          "comment flagged": "This comment has been flagged!",
          "notifications": "Notifications",
          "notification details": "Notification Details",
          "profile": "Profile",
          "general setting": "General Settings",
          "login": "Login",
          "get notifications": "Get Notifications",
          "contact us": "Contact Us",
          "rate this app": "Rate this app",
          "licence": "Licence",
          "privacy policy": "Privacy Policy",
          "about us": "About Us",
          "logout": "Logout",
          "edit profile": "Edit Profile",
          "update profile": "Update Profile",
          "updated successfully": "Updated Successfully",
          "enter new name": "Enter new name",
          "logout title": "Do you really want to logout from the app?",
          "yes": "Yes",
          "no": "No",
          "language": "Language",
          "select language": "Select Language",
          "buy now": "Purchase this app",
          "buy now subtitle":
              "Buy the full source code here and build the app for your country",
          "facebook": "Facebook Page",
          "youtube": "Youtube Channel",
          "no notifications": "No notifications found",
          "no blogs": "No blogs found",
          "no playing history found": "No Playing History Found",
          "playing history": "Playing History",
          "your reward": "Your Reward",
          "quest type": "Quest Type",
          "home": "Home",
          "reward": "Reward",
          "history": "History",
          "waiting loading data...": "Waiting Loading Data...",
          "waiting.....": "waiting.....",
          "my quest": "My Quest",
          "minutes": "minutes",
          "buy": "Buy",
          "item": "Item:",
          "quantity": "Quantity",
          "enter voucher here": "Enter voucher here",
          "total price": "Total price",
          "payment status": "Payment status",
          "not yet paid": "Not yet paid",
          "play code": "Play Code : ",
          "copy": "Copy",
          "cofirm payment": "Cofirm payment",
          "cofirm": "Confirm",
          "play now": "Play Now"
        },
        'vn': {
          "welcome message":
              "Khám phá mọi địa điểm nổi tiếng ở Việt Nam và tìm các khách sạn và nhà hàng lân cận một cách dễ dàng nhất. Nhận chỉ đường theo thời gian thực, chi phí ước tính, blog du lịch, v.v.",
          "welcome to": "Chào mừng đến với",
          "intro-title1": "Không quan trọng bạn đang ở đâu",
          "intro-title2": "Khám phá Nội dung lân cận",
          "intro-title3": "Hướng dẫn du lịch theo thời gian thực",
          "intro-description1":
              "Truy cập thông tin quan trọng về điểm đến của bạn trước và trong chuyến du lịch ...",
          "intro-description2":
              "Khám phá các khách sạn và nhà hàng lân cận gần mọi điểm du lịch bằng cách dễ dàng nhất ...",
          "intro-description3":
              "Nhận chỉ đường, chi phí và những thứ khác liên quan đến du lịch ở một nơi ...",
          "get started": "Bắt đầu",
          "explore country": "Khám phá Việt Nam",
          "search places": "Tìm kiếm quest",
          "popular places": "Địa điểm nổi tiếng",
          "special state-1 places": "Địa điểm ở Sylhet",
          "special state-2 places": "Địa điểm ở Chittagong",
          "recently added": "Đã thêm gần đây",
          "recommended places": "Địa điểm được đề xuất",
          "people like this": "Mọi người thích điều này",
          "todo": "Việc cần làm",
          "you may also like": "Bạn cũng có thể thích",
          "travel guide": "Hướng dẫn du lịch",
          "nearby hotels": "Khách sạn lân cận",
          "nearby restaurants": "Nhà hàng lân cận",
          "steps": "Các bước",
          "estimated cost = ": "Chi phí ước tính =",
          "distance = ": "Khoảng cách = ",
          "no hotels found": "Không tìm thấy khách sạn",
          "no restaurants found": "Không tìm thấy nhà hàng",
          "we didn't find any nearby hotels in this area":
              "Chúng tôi không tìm thấy bất kỳ khách sạn lân cận nào trong khu vực này",
          "we didn't find any nearby restaurants in this area":
              "Chúng tôi không tìm thấy bất kỳ nhà hàng lân cận nào trong khu vực này",
          "user reviews": "Đánh giá của người dùng",
          "write a review": "Viết đánh giá",
          "no internet": "Không có kết nối mạng!",
          "no comments found": "Không tìm thấy nhận xét nào",
          "be the first to comment": "Hãy là người đầu tiên nhận xét",
          "recently added places": "Địa điểm được thêm gần đây",
          "search & explore": "Tìm kiếm & Khám phá Địa điểm",
          "recent searchs": "Các Tìm kiếm Gần đây",
          "search for places": "Tìm kiếm địa điểm",
          "search-description":
              "Bạn chưa tìm kiếm bất kỳ mục nào. \n Hãy thử ngay bây giờ - chúng tôi sẽ giúp bạn!",
          "we have found": "Chúng tôi đã tìm thấy",
          "no places found": "Không tìm thấy địa điểm",
          "try again": "Thử lại!",
          "states": "Bang",
          "blogs": "Blog",
          "bookmarks": "Dấu trang",
          "saved places": "Địa điểm đã lưu",
          "saved blogs": "Blog đã lưu",
          "sign in first": "Đăng nhập trước",
          "sign in to save your favourite places here":
              "Đăng nhập để lưu các địa điểm yêu thích của bạn",
          "sign in to save your favourite blogs here":
              "Đăng nhập để lưu các blog yêu thích của bạn",
          "no blogs found": "Không tìm thấy blog",
          "save your favourite places here": "Lưu địa điểm yêu thích của bạn",
          "save your favourite blogs here": "Lưu các blog yêu thích của bạn",
          "skip": "Bỏ qua",
          "check your internet connection!":
              "Kiểm tra kết nối Internet của bạn!",
          "something is wrong. please try again.":
              "Đã xảy ra lỗi. Vui lòng thử lại.",
          "sign in": "Đăng nhập",
          "cancel": "Hủy bỏ",
          "no sign in title": "Đăng nhập trước để truy cập tính năng này",
          "no sign in subtitle":
              "Bạn chưa đăng nhập. Vui lòng đăng nhập để mở khóa tính năng này",
          "comments": "Nhận xét",
          "write a comment": "Viết bình luận",
          "no content": "Không tìm thấy nội dung",
          "delete?": "Xóa bỏ?",
          "delete from database?": "Bạn muốn xóa mục này?",
          "flag this comment": "Gắn cờ cho nhận xét này",
          "unflag this comment": "Bỏ gắn thẻ cho nhận xét này",
          "report": "Báo cáo",
          "delete": "Xóa",
          "report-info":
              "Báo cáo của bạn đã được gửi thành công tới quản trị viên",
          "report-info1":
              "Cảm ơn bạn đã báo cáo. Chúng tôi sẽ trả lời trong vòng 24 giờ.",
          "report-guest": "Đăng nhập là Bắt buộc!",
          "report-guest1": "Bạn phải đăng nhập để báo cáo về mọi nhận xét",
          "comment flagged": "Nhận xét này đã bị gắn cờ!",
          "notifications": "Thông báo",
          "notification details": "Chi tiết thông báo",
          "profile": "Hồ sơ",
          "general setting": "Cài đặt chung",
          "login": "Đăng nhập",
          "get notifications": "Nhận thông báo",
          "contact us": "Liên hệ với chúng tôi",
          "rate this app": "Xếp hạng ứng dụng này",
          "licence": "Giấy phép",
          "privacy policy": "Chính sách bảo mật",
          "about us": "Về chúng tôi",
          "logout": "Đăng xuất",
          "edit profile": "Chỉnh sửa hồ sơ",
          "update profile": "Cập nhật hồ sơ",
          "updated successfully": "Đã cập nhật thành công",
          "enter new name": "Nhập tên mới",
          "logout title": "Bạn có thực sự muốn đăng xuất khỏi ứng dụng không?",
          "yes": "Có",
          "no": "Không",
          "language": "Ngôn ngữ",
          "select language": "Chọn ngôn ngữ",
          "buy now": "Mua ứng dụng này",
          "buy now subtitle":
              "Mua toàn bộ mã nguồn tại đây và xây dựng ứng dụng cho quốc gia của bạn",
          "facebook": "Facebook",
          "youtube": "Youtube",
          "no notifications": "Không tìm thấy thông báo",
          "no blogs": "Không tìm thấy blog nào",
          "no playing history found": "Không tìm thấy lịch sử chơi nào",
          "playing history": "Lịch sử chơi",
          "your reward": "Phần thưởng của bạn",
          "quest type": "Các Thể Loại",
          "home": "Trang chủ",
          "reward": "Quà",
          "history": "Lịch sử",
          "waiting loading data...": "Đang tải dử liệu...",
          "waiting.....": "Đang tải.....",
          "my quest": "Quest của tôi",
          "minutes": "phút",
          "buy": "Mua",
          "item": "Vật phẩm:",
          "quantity": "Số Lượng",
          "enter voucher here": "Nhập mã giảm giá",
          "total price": "Tổng tiền",
          "payment status": "Thông tin thanh toán",
          "not yet paid": "CHƯA THANH TOÁN",
          "play code": "Mã chơi : ",
          "copy": "Sao chép",
          "cofirm payment": "Xác nhận thanh  toán",
          "cofirm": "Xác nhận",
          "play now": "Chơi ngay"
        }
      };
}
